version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: front_react
    ports:
      - 3000:3000
    tty: true

  backend:
    build: ./backend
    container_name: back_fastapi
    ports:
      - 8000:8000